name: master-workflow

on:
 push:
  branches:
    - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.7.1

    - name: serverless deploy
      uses: vlaaaaaaad/github-action@python-too
      with:
         args: "deploy --stage master"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_VERIFICATION_TOKEN: ${{ secrets.SLACK_VERIFICATION_TOKEN }}
        INTERVIEW_AVAIL_CAL: ${{ secrets.INTERVIEW_AVAIL_CAL }}
        SVC_ACCOUNT_PRIV_KEY_ID: ${{ secrets.SVC_ACCOUNT_PRIV_KEY_ID }}
        SVC_ACCOUNT_PRIV_KEY: ${{ secrets.SVC_ACCOUNT_PRIV_KEY }}
        SVC_ACCOUNT_EMAIL: ${{ secrets.SVC_ACCOUNT_EMAIL }}
        SVC_ACCOUNT_ID: ${{ secrets.SVC_ACCOUNT_ID }}
        SVC_ACCOUNT_X509_CERT_URL: ${{ secrets.SVC_ACCOUNT_X509_CERT_URL }}
