name: dev-branch-workflow

on:
 push:
  branches:
    - '*'
    - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: python-syntax-check
      uses: cclauss/Find-Python-syntax-errors-action@master

    - name: python-lint
      uses: CyberZHG/github-action-python-lint@0.0.2
